version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.streamlit-db
    ports:
      - "8503:8501"
    depends_on:
      - db

  db:
    image: postgres:18-alpine
    env_file:
      - .env
    volumes:
      - mydb_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mydb_data: